---
title: "Course Schedule"
description: "Weekly schedule for the GEOG 279 course."
---

[Course Syllabus](syllabus/GEOG279_Syllabus_Fall_24.pdf)

| **Week** | **Day**      | **Topic**                                   | **Readings**                                                                                                                                                                  | **Slides** | **Notes**       |
|----------|--------------|---------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|-----------------|
| 0        | Thursday     | Why causal analysis?                       |                                                                                                                                                                               | [Why causal analysis? Slides](slides/Intro_to_causality.pptx) |                 |
| 1        | Tuesday      | Potential outcomes framework               | [Ferraro et al., 2018](https://www.pnas.org/doi/full/10.1073/pnas.1805563115) <br> <span style="color: gray; font-style: italic;">Skim: [Holland, P.W. (1986)](https://doi.org/10.2307/2289064), "Statistics and Causal Inference."</span> | [The Challenge of Impact Assessment Slides](slides/1B - The Challenge of Impact Assessment.pptx) |                 |
|          | Thursday     | <span style="color: red;">**No Class**</span> |                                                                                                                                                                               |            | <span style="color: red;">No Class</span> |
| 2        | Tuesday      | Causal Diagrams                            | [Brodie, J.F., et al. (2023)](https://www.nature.com/articles/s41586-023-06410-z), "Landscape-Scale Benefits of Protected Areas for Tropical Biodiversity." <br>[The Effect Book](https://theeffectbook.net/index.html) (**ch6 & 7**)                                                                                                                      | [DAG Slides](slides/Directed_Acyclic_Graph_(DAG).pptx) |                 |
|          | Thursday     | Causal Diagrams                            | [The Effect Book](https://theeffectbook.net/index.html) (**ch6 & 7**)                        |            | **Assignment 1 due Thurs, Oct 10 (includes paper topic)** |
| 3        | Tuesday      | Randomized Control Trials (RCT) and Power Calculations | [Impact Evaluation in Practice](books/impact_eval_book.pdf) (**ch4,p63-86**)                                                                                                           | [Randomized Control Trials Slides](slides/2A - Randomized Control Trials.pptx) |                 |
|          | Thursday     | Randomized Control Trials (RCT) and Power Calculations | [Impact Evaluation in Practice](books/impact_eval_book.pdf) (**ch15,p261-287**)                                                                                                          |            |                 |
| 4        | Tuesday      | Matching and Synthetic Controls            | [Honey-Rosés, J., et al. (2011)](https://conbio.onlinelibrary.wiley.com/doi/10.1111/j.1523-1739.2011.01729.x) <br> <span style="color: gray; font-style: italic;">Skim: [Rubin, D. B. (1974)](journals/1975-06502-001.pdf), "Original Work"</span> | [Matching Estimators Slides](slides/2B - Matching Estimators.pptx) |                 |
|          | Thursday     | Matching and Synthetic Controls            | [Alberto Abadie, Alexis Diamond & Jens Hainmueller (2012)](https://www.tandfonline.com/doi/citedby/10.1198/jasa.2009.ap08746?scroll=top&needAccess=true) | [Synthetic Controls Slides](slides/Synthetic Controls.pptx) | |
| 5        | Tuesday      | Differences-in-Differences (DID) and Staggered roll-out  | [Wauchope HS, Jones JPG, et al. (2022)](https://pubmed.ncbi.nlm.nih.gov/35444280/)                                                                                          | [Slides](#) |                 |
|          | Thursday     | Differences-in-Differences and Staggered roll-out | [Jonathan Roth, Pedro H.C. Sant’Anna, Alyssa Bilinski, John Poe. (2023)](https://doi.org/10.1016/j.jeconom.2023.03.008)                                                     |            | **Assignment 2 due Tues, Oct 29** |
| 6        | Tuesday      | Instrumental Variables and Regression Discontinuity Design | [Mellon, 2024](https://doi.org/10.1111/ajps.12894)                                                                                                                           | [Slides](#) |                 |
|          | Thursday     | Instrumental Variables and Regression Discontinuity Design | [Noack, Frederik, Ashley Larsen, Johannes Kamp, and Christian Levers. (2022)](https://onlinelibrary.wiley.com/doi/full/10.1111/ajae.12274)                                   |            | **Assignment 3 due Thurs, Nov 7** |
| 7        | Tuesday      | Standard errors and spatial considerations  |                                                                                                                                                                               | [Slides](#) |                 |
|          | Thursday     |                                           |                                                                                                                                                                               |            |                 |
| 8        | Tuesday      | Remote Sensing and Machine Learning in Causal Analysis | [Proctor, J., Carleton, T., Sum, S. (2023)](https://www.nber.org/papers/w30861?utm_campaign=ntwh&utm_medium=email&utm_source=ntwg3)                                          | [Slides](#) |                 |
|          | Thursday     | Remote Sensing and Machine Learning in Causal Analysis | [Baylis, K., T. Heckelei, H. Storm. (2021)](https://doi.org/10.1016/bs.hesagr.2021.10.007)                                                                                  |            | **Assignment 4 due Thurs, Nov 21** |
| 9        | Tuesday      | Machine Learning in Causal Analysis        | -                                                                                                                                                                             | [Slides](#) |                 |
|          | Thursday     | <span style="color: red;">**No Class** (Thanksgiving)</span> |                                                                                                                                                                               |            | <span style="color: red;">Thanksgiving</span> |
| 10       | Tuesday      | Final Presentations                       | -                                                                                                                                                                             | [Slides](#) | **Final Paper Proposal due Dec 9th** |