---
title: "GEOG 279 Course Overview"
description: |
  Causal Analysis in Space
site: distill::distill_website
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```


# [Instructor Information](#instructor-information)

::: {.callout-note}
- **Instructor**: Kathy Baylis
- **Office Location**: 5808 Ellison Hall
- **Office Hours**: 9-10 AM on Tuesdays or by appointment
- **Term**: Fall 2024
:::

# [Course Description](#course-description)

**GEOG 279: Applied Statistics for Geography (Introduction to Causal Analysis in Space)** focuses on developing skills in causal analysis within spatial contexts. This course introduces students to key concepts in causal inference, statistical methodologies, and their applications in spatial analysis. Throughout the quarter, students will engage with various statistical techniques, including randomized control trials (RCT), matching, synthetic controls, differences-in-differences (DID), instrumental variables, regression discontinuity design, and machine learning (ML).

The course will involve a series of readings, assignments, and practical applications to deepen the understanding of causal analysis in geography. Students will learn to:

- Understand the potential outcomes framework for causal inference.
- Utilize causal diagrams to represent relationships in spatial data.
- Design and implement RCT and power calculations for spatial data.
- Apply matching and synthetic control methods to estimate causal effects.
- Use DID and instrumental variables in spatial statistics.
- Incorporate ML and remote sensing in causal analysis for geographical studies.

## [Course Goals](#course-goals)

By the end of this course, students will be able to:

1. Interpret and conduct causal analyses in spatial data.
2. Implement various statistical methods for causal inference in geographical research.
3. Apply statistical tools and methodologies to real-world spatial problems.
4. Develop skills in presenting and discussing statistical findings related to causal analysis.
5. Critically assess and apply different causal inference methods to geographic data.
