---
title: "Course Schedule"
description: "Weekly schedule for the GEOG 279 course."


---
| **Week** | **Topic**                                                  | **Readings**                                                                                                                                                                                                                                                                                                  | **PPT Slides** |
| -------- | ---------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------- |
| **0**    | Why Causal Analysis?                                       | Introduction to causal analysis.                                                                                                                                                                                                                                                                              | [Link](#)      |
| **1**    | Potential Outcomes Framework                               | Ferraro et al. 2018: [Link](#)   - Skim: Holland, P. W. (1986). "Statistics and Causal Inference." JASA, 81(396), *945*–960. Link                                                                                                                                                                             |                |
| **2**    | Causal Diagrams                                            | Tuesday: Huntington, Nick, *The Effect* Chapters 6 and 7. [Link](#)   - Thursday: Brodie, Jedediah F., et al. (2023). "Landscape-Scale Benefits of Protected Areas." Nature, 620(79*75), 8*07–12. Link                                                                                                        |                |
| **3**    | Randomized Control Trials and Power Calculations           | Tuesday: Chapter 4 from Gertler, Paul J., et al. (2016). *Impact Evaluation in Practice.*   - Thursday: Chapter 15 from the same book.                                                                                                                                                                        |                |
| **4**    | Matching and Synthetic Controls                            | Tuesday: Honey-Rosés, Jordi, et al. (2011). "A Spatially Explicit Estimate of Avoided Forest Loss." *Conservation Biology*, 25(5), 1032–43. [Link](#)   - Thursday: Abadie, Alberto, et al. (2010). "Synthetic Control Methods for Comparative Case Studies." JASA, 105(490)*, 49*3–505.                      |                |
| **5**    | Differences-in-Differences and Staggered Roll-Out          | Tuesday: Wauchope, Hannah S., et al. (2022). "Protected Areas Have a Mixed Impact on Waterbirds, but Management Helps." *Nature*, 605(7908), 103–7. [Link](#)   - Thursday: Roth, Jonathan, et al. (2023). "What’s Trending in Difference-in-Differences?" Journal of Eco*nometrics, 235(2), 2218*-2244. Link |                |
| **6**    | Instrumental Variables and Regression Discontinuity Design | Tuesday: Mellon, Jonathan. (2024). "Rain, Rain, Go Away: 194 Potential Exclusion-Restriction Violations." *AJPS*. [Link](#)   - Thursday: Noack, Frederik, et al. (2022). "A Bird’s Eye View of Farm Size and Biodiversity." AJAE, 104(4), *1460*–84. Link                                                    |                |
| **7**    | Standard Errors and Spatial Considerations                 | Introduction to spatial considerations in statistical models.                                                                                                                                                                                                                                                 |                |
| **8**    | Remote Sensing and Machine Learning in Causal Analysis     | Proctor, J., et al. (2023). "Parameter Recovery Using Remotely Sensed Variables." *NBER Working Paper.*   - Skim: Baylis, K., et al. (2021). "Machine Learning in Agricultural Economics." Handbook of Ag*ricultural Economics. Link*                                                                         |                |
| **9**    | Machine Learning in Causal Analysis                        | No class on Thurs, Nov 28: Thanksgiving.                                                                                                                                                                                                                                                                      |                |
| **10**   | Presentations                                              | Final Paper Proposal: Due Dec 9.                                                                                                                                                                                                                                                                              |                |

